name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    env:
      # Adjust if your settings module path is different
      DJANGO_SETTINGS_MODULE: Django_Documentation.settings
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt"
            pip install -r requirements.txt
          else
            echo "No requirements.txt found; installing minimal dependencies"
            pip install "Django>=4.2,<6" flake8
          fi

      - name: Sanity check
        run: |
          python -V
          python -c "import django; print('Django', django.get_version())"

      - name: Run migrations
        run: python manage.py migrate --noinput --verbosity 2

      - name: Lint (flake8)   # keep non-blocking while you stabilize
        continue-on-error: true
        run: flake8 .

      - name: Run tests
        run: python manage.py test -v 2
